### ISSUE TITLE
Allow records to have two datatypes

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#1028]
In our new model, scanned resources with raster children will produce a resource that is both an "Image" and a "Raster". A single record should show up when faceting on etiher.

This is handled in the new 4.0 GBL schema, not sure how this would be done in GBL 3.x.

The ScannedMap record needs to be able to have a metadata service for the tiles.

The ScannedMap record needs to be able to be discoverable as both a raster and a scanned map.

## Success Criteria

A user can limit to Raster results and get a Mosaic (MapSet w/ ScannedMaps that have Rasters) back.

Specifically, https://maps-staging.princeton.edu/?utf8=%E2%9C%93&f%5Blayer_geom_type_s%5D%5B%5D=Raster&search_field=all_fields&q=the+balkans+%5Band%5D+turkey+%3A+g.s.g.s.+no.+2097+%2F+war+office.+general+staff.+geographical+section+%28fixture+resource%29 should return one result (https://maps-staging.princeton.edu/catalog/princeton-fk4544658v) - it should also return for Format: Image.

**Comment by hackartisan** [comment]
Deployment strategy:
1. add copyfields to schema from `layer_geom_type_s` to `layer_geom_type_sm` and `layer_geom_type_tmi`.
2. reindex
3. deploy everything else in https://github.com/pulibrary/pulmap/pull/1075/files
4. deploy https://github.com/pulibrary/figgy/pull/5047
5. reindex again

**Comment by tpendragon** [comment]
@hackartisan That looks great!

**Comment by eliotjordan** [comment]
Complete.
