### ISSUE TITLE
Add back the bounding box facet indicator

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulmap#1054]
In default gbl when you interact with the map it adds a facet label indicating you've done so. I think we've removed it but it would be helpful information, especially given the zoom-out-when-paging-through-results behavior.

example on harvard's site: https://hgl.harvard.edu/?bbox=10.068769+25.707831+54.365644+52.420488&f%5Bdct_spatial_sm%5D%5B%5D=Balkan+Peninsula&page=4&q=balkans&search_field=all_fields

**Comment by tpendragon** [comment]
We're not sure users will understand the long coordinate facets - revisit after closing #1035
