### ISSUE TITLE
Display rights statement on show page for each item

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulmap#1060]
We need to be sure that we’re displaying the rights statements (both the PUL statement and the [rightstatements.org](http://rightstatements.org/) statement) on the show pages for each item.

When this is closed please ping @jpstroop 

## Sudden priority justification

Requirement came out of a meeting with general counsel regarding copyright statements for not-yet ingested vector resources.

## Implementation Strategy

1. Index right statements text & PUL rights boilerplate into Geoblacklight documents from Figgy.
2. Render the rights statements/boilerplate.

**Comment by sdellis** [comment]
@hackartisan do you know where we can find the PUL Statement and the appropriate  Rightstatements.org statement we should use?

**Comment by tpendragon** [comment]
@sdellis https://github.com/pulibrary/figgy/blob/main/config/authorities/rights_statement.yml

**Comment by tpendragon** [comment]
The PUL boilerplate is here: https://github.com/pulibrary/figgy/blob/94d66c8b49436d49931d998666c503c80eac2f69/config/locales/en.yml#L111

**Comment by tpendragon** [comment]
Indexing is blocked until sync is fixed - #5011
