### ISSUE TITLE
Reindex all production data

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulmap#1103]
Child of #1028

- [ ] external content
  - [x] Stanford (need to pull from open geometadata because of access restrictions)
  - [x] Big 10 (need to pull each individually from open geometadata because their feed is on aardvark)
  - [x] Harvard
  - [x] Columbia (indexed from Pulmap)
  - [ ] MassGIS (from earthworks) (partial - hit stanford access limits)
  - [x] Tufts (indexed from pulmap 🤷‍♂️ )
  - [x] NYU / Baruch
  - [x] Cornell
  - [x] University of Texas (geoblacklight site is down: https://geodata.lib.utexas.edu/)
  - [x] MIT
  - [x] University of Colorado Boulder
  - [x] Berkeley
- [x] figgy content

For external content:
- Some of these are known to work and are scheduled in schedule.rb -- we can just trigger those.
- Some of them are known to not be working but there is existing data in the index, so we need to get these in (programmatically and added to schedule.rb if possible, but manually if needed).
- Delete each data source before pulling the records fresh to ensure we have the most up to date index.

**Comment by eliotjordan** [comment]
Created two follow-up tickets:
https://github.com/pulibrary/pulmap/issues/1107

**Comment by eliotjordan** [comment]
Complete.
