### ISSUE TITLE
[Pulmap/production] OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=52.203.197.75:443 state=error: certificate verify failed (certificate has expired)

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#1124]
## Backtrace

    line 85 of [PROJECT_ROOT]/lib/tasks/pulmap.rake: block (3 levels) in <top (required)>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/90047907)

## Success Criteria

We talk to MIT, ask them to fix their certificate, and when they do we stop getting this error and close this ticket.

**Comment by sdellis** [comment]
According to @eliotjordan this appears to be an expired SSL cert for the MIT GeoBlacklight instance.

**Comment by tpendragon** [comment]
This was from geodata.mitlib.net, which has renewed its SSL cert, we can close this.
