### ISSUE TITLE
error when downloading geojson file on princeton-pc289t529

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#1144]
Error when you try to download the geojson on https://maps.princeton.edu/catalog/princeton-pc289t529, Net-Zero America bulk transmission expansions between metropolitan statistical areas for 100% renewable scenario (base land use), 2050

## Backtrace

    line 10 of [PROJECT_ROOT]/config/initializers/download.rb: initiate_download

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/93013040)

**Comment by tpendragon** [comment]
Can't reproduce.
