### ISSUE TITLE
[Pulmap/production] NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#1147]
## Backtrace

    line 155 of [PROJECT_ROOT]/app/helpers/advanced_helper.rb: guided_search
    line 208 of [PROJECT_ROOT]/app/helpers/advanced_helper.rb: render_constraints_query
    line 10 of [PROJECT_ROOT]/app/views/catalog/_constraints.html.erb: _app_views_catalog__constraints_html_erb___3854097568605852427_89480

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/87838410)

**Comment by hackartisan** [comment]
no data
