### ISSUE TITLE
[Pulmap/production] TypeError: String does not have #dig method

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#1150]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/93954943)

**Comment by sdellis** [comment]
Is there any way that we can filter these query string params so they don't report errors?

**Comment by hackartisan** [comment]
We're deciding to ignore these, it would be pretty hard to try to filter them and we don't think they pose a real risk.
