### ISSUE TITLE
[Pulmap/production] ActionController::ActionControllerError: Cannot redirect to nil!

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#1153]
## Backtrace

    line 8 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: cas

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/74233877)

**Comment by hackartisan** [comment]
This error happens because of the gem used in https://github.com/pulibrary/pulmap/pull/910
