### ISSUE TITLE
Upgrade Redis

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulmap#1157]
We run Redis locally for pulmap

Steps for staging:

- [x] Check out the dependabot PR https://github.com/pulibrary/pulmap/pull/1152 locally. Update the lando config to use redis 7. Update the sidekiq configuration. example PR: https://github.com/pulibrary/dpul/pull/1452 (except note pulmap doesn't use sidekiq pro)
- [x] turn off workers for the app
- [x] Note the number of jobs processed today on the sidekiq dashboard (10)
- [x] Enqueue some jobs that won't actually do anything (pulmap will simply ack unknown event types) (I enqueued this 5 times): 
```
bundle exec cap staging rails:console
IndexJob.perform_later({"event" => "UNKNOWNEVENT"}) # do this a bunch of times
```
- [x] pull princeton_ansible main, then run the app's usual ansible playbook, then run the upgrade_redis playbook.
- [x] deploy the sidekiq upgrade branch. This will also restart workers
- [x] check the number of jobs processed; it should go up otherwise we've lost redis data (yep -- went up to 15)

Troubleshooting: You can use the full url from one box to check the redis connection to the other box, e.g. `redis-cli -u redis://dpul-staging1.princeton.edu:6379/0 INFO`

Prod:

- [x] turn off workers for the app
- [x] pull princeton_ansible main, then run the app's usual ansible playbook, then run the upgrade_redis playbook.
- [x] merge https://github.com/pulibrary/pulmap/pull/1152
- [x] deploy main. This will also restart workers

**Comment by hackartisan** [comment]
done
