### ISSUE TITLE
Thumbnails are all broken in search results

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#1159]
Looks like something is wrong with our google cloud credentials.

https://github.com/pulibrary/pulmap/blob/efc9c83937c0f873c3f35e474f37b17c3b2bec83/config/storage.yml

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/92677499)

## Sudden priority justification
The site is missing core functionality

see also #1141

**Comment by hackartisan** [comment]
These errors correspond to the date stamp on the server's credentials file. Maybe an old file was put back in place?

**Comment by hackartisan** [comment]
The timing is correlated to running playbooks to reduce datadog noise on all applications. (https://github.com/pulibrary/princeton_ansible/pull/3923)
