### ISSUE TITLE
Provision Jammy VMs

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulmap#1187]
# Reasoning

We need to upgrade all our boxes to Jammy; we're starting to be unable to get apt packages, etc.

# Boxes to Migrate

These are the names of the existing boxes. We can change the names to use current conventions, suggestions inline.

## Staging
`maps-staging1` => migrate to `maps-staging2`?

## Production
`maps1` => migrate to `maps-prod1`
`maps2` => migrate to `maps-prod2`

**Comment by tpendragon** [comment]
Definitely the redis one

**Comment by acozine** [comment]
I added rules for Redis for all three VMs for the library network, so we can run local Redis or use the shared Redis in future.

Maps VMs should be ready to rock and roll in a few minutes.

**Comment by tpendragon** [comment]
We're reopening these, but just so we can keep track of doing the provisioning of these now that they're made.
