### ISSUE TITLE
Rsync missing maps from libimages to libimages1

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#155]
There are some maps on libimages that are missing on libimages1. Rsync to copy them over.

**Comment by jpstroop** [comment]
May be worth noting: until a couple of months ago I was under the impression that Phil was synchronizing these servers at a regular (and presumably tight) interval. I was wrong. He did it once when we set up the second machine, and that was it.

**Comment by eliotjordan** [comment]
Good to know. The discrepancy is quite large.

**Comment by eliotjordan** [comment]
Done. Issue was primarily with malformed iiif urls.
