### ISSUE TITLE
Review UI

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#168]

**Comment by eliotjordan** [comment]
@axamei, when you have time.

**Comment by axamei** [comment]
The topics section on the homepage need some adjustments for smaller viewports:

<img width="790" alt="screen shot 2016-07-22 at 12 08 39 pm" src="https://cloud.githubusercontent.com/assets/8161144/17063478/7ad613ea-5005-11e6-9d03-a26318bf349b.png">
<img width="360" alt="screen shot 2016-07-22 at 12 08 23 pm" src="https://cloud.githubusercontent.com/assets/8161144/17063479/7ad9a550-5005-11e6-89b7-28a47b24a552.png">

**Comment by eliotjordan** [comment]
Oh! That doesn't look great. Thanks for the suggestion. See #174.
