### ISSUE TITLE
Add matomo analytics

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#25]

**Comment by kevinreiss** [comment]
@eliotjordan Let me know what domain you need a tracking code for and I can add it our institutional account.

**Comment by eliotjordan** [comment]
@kevinreiss Do you set up tracking just for production sites or for development sites as well?

**Comment by kevinreiss** [comment]
We can do it for any domain. It doesn't matter. Generally only for
production, but if you want it for a test domain that is fine.
