### ISSUE TITLE
Fix metadata display functionality

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#260]
- [x] FGDC metadata link is not working. Metadata FileSet is not downloadable w/o CAS. Despite it's visibility.
- [ ] Use XSLT to format metadata?

**Comment by eliotjordan** [comment]
Partially fixed by: https://github.com/pulibrary/plum/pull/1358

**Comment by jrgriffiniii** [comment]
I believe that this was resolved by https://github.com/geoblacklight/geoblacklight/pull/555 (and the subsequent https://github.com/geoblacklight/geoblacklight/pull/567).  This should only now be blocked by the next release of GeoBlacklight.
