### ISSUE TITLE
Expand filter options on search results page

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#34]
Place filter options/facets below searchbar.

Include most common facets (e.g. subject as select) next to search button outside of toggle area.

See: http://www.trulia.com/for_rent/Princeton,NJ/map_v

**Comment by axapu** [comment]
@eliotjordan Is there a way to break apart the facets? We want the subject facet to be next to search bar and not in the expanded toggled view. Also, can we change the facets to be select elements instead of lists of links?
