### ISSUE TITLE
Zoom level should influence relevancy

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulmap#354]
Consider how zoom level might influence relevancy of items. When zoomed out, items with larger coverage area might be favored, and when zoomed in, smaller coverage areas might be favored.

**Comment by christinach** [comment]
https://lucene.apache.org/solr/guide/7_1/spatial-search.html
https://lucene.apache.org/solr/guide/7_1/spatial-search.html
https://lucene.apache.org/solr/guide/7_1/spatial-search.html#distance-sorting-or-boosting-function-queries
