### ISSUE TITLE
Remove URL query strings for pages embedding the UniversalViewer

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulmap#391]
For cases in which a IIIF Manifest is used to render a digitized or scanned item using the UniversalViewer, the URL query string specifying (amongst other information) the region of the image being rendered cannot be used to provide a persistent mode for viewing the image resource.

![pulmap_issues_391_screenshot](https://user-images.githubusercontent.com/1443986/29683088-32ef3074-88db-11e7-89a1-eaa8a3567177.png)

**Comment by sdellis** [comment]
@jrgriffiniii  which version of the UV is this? The URL sharing behavior works properly on  universalviewer.io examples.
