### ISSUE TITLE
Contact Us form should not be generic

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulmap#406]
Subject should be "GIS/Maps" and should be routed to Eliot and Wangyal.

**Comment by tampakis** [comment]
Make a custom one ala Orangelight

**Comment by sdellis** [comment]
Given the amount of RBSC maps that will be in here, I would definitely investigate the LibAnswers option as well. RBSC uses this to manage reference and you can easily create a UI widget that will route inquiries and correspondence appropriately.

**Comment by sdellis** [comment]
I also know that @jpstroop wanted to lean more on vendors for common/generic solutions where appropriate. I think this falls into that category, especially since it's a feature needed on many of our apps and we should be thinking about a more centralized solution.

**Comment by tampakis** [comment]
Good point @sdellis. My initial guess is that we'll have 3 types of input from the contact us form:
 - Info about accessing rare books maps (Gabriel)
 - Info about maps center maps and datasets or how to use the app (Wangyal)
 - feedback and reporting system errors (Wangyal and us, maybe lsupport)

We already have the mail server set up and we can reuse a lot of the code in the Orangelight feedback form. I think that the "routing" is relatively simple and can be configured via dropdown options.
