### ISSUE TITLE
[Pulmap/production] Error viewing relations

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#473]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/35737474)

**Comment by eliotjordan** [comment]
This looks like a bug in Geoblacklight with the relations controller. If the layer slug has a colon in it, rsolr throws an error.

**Comment by eliotjordan** [comment]
Opened an issue on the GeoBlacklight gem about this: https://github.com/geoblacklight/geoblacklight/issues/573

**Comment by jrgriffiniii** [comment]
https://github.com/geoblacklight/geoblacklight/issues/573 was resolved by merging https://github.com/geoblacklight/geoblacklight/pull/631, therefore I'm uncertain as to why https://app.honeybadger.io/projects/54400/faults/35737474 is continuing to occur

**Comment by eliotjordan** [comment]
Should be closed now.
