### ISSUE TITLE
Metadata view doesn't load

### ISSUE THREAD

**Issue by tampakis** [pulibrary/pulmap#501]
Clicking the metadata button from the show page hangs: https://maps.princeton.edu/catalog/princeton-r781wh718

The page itself doesn't load: https://maps.princeton.edu/catalog/princeton-r781wh718/metadata

**Comment by eliotjordan** [comment]
Fixed

**Comment by eliotjordan** [comment]
This is a problem when figgy is slow, because it takes awhile to download the xml document. What doesn't work is the "download" button. Clicking it opens a duplicate tab for the document.
