### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#51]
Create real logo for LIME. Perhaps this can wait until the name is 100% approved.

**Comment by eliotjordan** [comment]
Instead of branding the app like 'Earthworks', a simple description might be better. "Maps and Geospatial Data." Logoized. In a nice font. Etc...

**Comment by eliotjordan** [comment]
Remove the logo instead.

**Comment by axamei** [comment]
Some options:

Font used is Oswald in uppercase or title case (found on front page). Serif font is Princeton Monticello. There's a few icons we can work with. @eliotjordan Let me know if any of these are close to what you were thinking. 

<img width="1157" alt="screen shot 2016-10-04 at 1 47 52 pm" src="https://cloud.githubusercontent.com/assets/8161144/19085692/3a99b110-8a39-11e6-93cc-a7614f491cc8.png">
<img width="1161" alt="screen shot 2016-10-04 at 1 47 32 pm" src="https://cloud.githubusercontent.com/assets/8161144/19085694/3a9a5be2-8a39-11e6-9a40-e05d9ab54893.png">
<img width="1159" alt="screen shot 2016-10-04 at 1 46 49 pm" src="https://cloud.githubusercontent.com/assets/8161144/19085693/3a99d442-8a39-11e6-9201-4464f148e352.png">
<img width="1161" alt="screen shot 2016-10-04 at 1 53 44 pm" src="https://cloud.githubusercontent.com/assets/8161144/19085960/4394e77a-8a3a-11e6-9073-5df9558cb813.png">
<img width="1160" alt="screen shot 2016-10-04 at 1 53 19 pm" src="https://cloud.githubusercontent.com/assets/8161144/19085961/4399a382-8a3a-11e6-96be-e704ad69172b.png">

**Comment by tampakis** [comment]
I like the globe!

**Comment by eliotjordan** [comment]
👏   Apologies for the late reply on this! I'm partial to [this one](https://cloud.githubusercontent.com/assets/8161144/19085693/3a99d442-8a39-11e6-9201-4464f148e352.png). How do you think that compass would look with a transparent background instead of the off-white? Just a thought.

**Comment by axamei** [comment]
I don't think it matters what the background color is. We can always adjust the color if the compass/icon itself.
