### ISSUE TITLE
Expand home page with other information

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#54]
Expand the bullets area on the home page. What can we add?

- Recent scans
- Recently added datasets
- ??

**Comment by eliotjordan** [comment]
@axapu Are you using refills at all in this project? On the Refills example page, the flexbox items look pretty nice. They might be useful for additional content like featured maps or new datasets.

**Comment by axapu** [comment]
I grabbed the placeholder from Refills. We can use the flex boxes and grid items instead of the icon bullet points.

**Comment by eliotjordan** [comment]
Closed by #166.
