### ISSUE TITLE
Sync thumbnails between servers

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#546]
Figure out strategy for syncing thumbnails between servers.
- Nightly thumbnail jobs
- Nightly rsync between maps1 and maps2.
- Shared thumbnail storage (doesn't seem ideal, but maybe using shared isilon drive is would work)

Sometimes thumbnails appear, and then disappear when reloading. I assume this means that the thumbnail is cached on one server and not the other.

**Comment by tpendragon** [comment]
Can you just put the image on the IIIF server and serve it?

**Comment by tpendragon** [comment]
There's a whole new thing going on.
