### ISSUE TITLE
Put space below search bar on index page

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#56]
Put a space between the search bar and the results on the index page.

**Comment by eliotjordan** [comment]
![3](https://cloud.githubusercontent.com/assets/784196/10890531/655a83ca-8166-11e5-802e-e06ba32a46ba.png)

**Comment by axapu** [comment]
Do we need this now that the search area has a white background?

**Comment by eliotjordan** [comment]
I don't think we need it now.
