### ISSUE TITLE
Browse all records... link is broken

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#604]
Link for browsing all related records is broken. An extra backslash is inserted into the identifier. Maybe an upstream issue?

**Comment by ewlarson** [comment]
We saw this in the B1G Geoportal too:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/issues/120

**Comment by tampakis** [comment]
Still an issue

**Comment by eliotjordan** [comment]
Example: https://maps.princeton.edu/catalog/princeton-hd76s2965

**Comment by tampakis** [comment]
Works after Geoblacklight upgrade: https://maps-staging.princeton.edu/catalog?f%5Bdc_source_sm%5D%5B%5D=princeton-hd76s2965
