### ISSUE TITLE
Fix item view map width issue

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#61]
When viewing an item without an attribute table (restricted or no viewer endpoint) the map size does not match the div width. Look at IIIF layout for a possible solution.

**Comment by eliotjordan** [comment]
![6](https://cloud.githubusercontent.com/assets/784196/10890949/3da2108e-8169-11e5-9631-e27bee38d8f8.png)

**Comment by axapu** [comment]
Map container stretches to full width if no table is present as sibling element. Removing column layout class names  is producing this error. Commenting this out until we find solution.
