### ISSUE TITLE
Remove bourbon and neat gems

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#618]
Probably just used for displaying "cards" on the home screen:

<img width="472" alt="Screenshot 2019-06-03 12 22 46" src="https://user-images.githubusercontent.com/784196/58821340-71dae580-85fa-11e9-9ff7-be6b147dc44c.png">

**Comment by christinach** [comment]
I'll continue with this issue and replace them with bootstrap 4 when we update to gbl 2.1.2. If we don't manage to update the gbl gem to 2.1.2, then I will continue with updating them to bootstrap 3.
