### ISSUE TITLE
Range limit facet isn't displaying correctly

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#64]
Range limit facet isn't displaying correctly. Perhaps this has to do with the drop down? Missing css? Perhaps is could be presented in a non-dropdown format? Whatever works.

**Comment by eliotjordan** [comment]
This is the working version from earthworks:

![screenshot 2015-11-02 15 02 13](https://cloud.githubusercontent.com/assets/784196/10892703/02ef578a-8173-11e5-9d54-1a7cd329f039.png)

**Comment by axapu** [comment]
Range slider should also be displayed like on pulsearch:
<img width="385" alt="screen shot 2015-11-03 at 12 12 51 pm" src="https://cloud.githubusercontent.com/assets/8161144/10915324/4369ecc4-8224-11e5-9fd4-bfa963f5fd00.png">
