### ISSUE TITLE
Fix styling on home page

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#652]

**Comment by christinach** [comment]
some of the problems I face:
- I'm not able to make the grid work in bs 4 , recognizing the columns in the navbar. the divs should be next to each other bulding the 12 col grid but they appera one below the other.
- When I use the 'navbar' class as a wrapping then the class 'l-branding__pul index-branding' takes a 411.86 px width and will not fill the 'navbar' which takes the full width of the screen in the background.
- When I remove the 'navbar' class (this doesn't look correct to me) then the class "l-branding__pul index-branding" takes the full width of the screen. (this is also how it works currently.)

**Comment by christinach** [comment]
ok, I updated to include the navbar wrapping in the 
```
<div class="l-branding__pul <%= layout_type %>-branding">
  <div class="<% unless index_layout? %>container<% end %> <%= layout_type %>-container ">
    <div class="navbar <%= navbar_type %>">
``
and things look much better.

**Comment by christinach** [comment]
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/9905193/59367911-18b23680-8d0b-11e9-96c9-302ba1be9a00.gif)

**Comment by christinach** [comment]
I improved it by using the BS4 dark background which is black like the rest of the PUL web applications.
![Screen Shot 2019-06-12 at 12 34 12 PM](https://user-images.githubusercontent.com/9905193/59369496-8b70e100-8d0e-11e9-8aaf-81b7237008e7.png)


![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/9905193/59369822-3a152180-8d0f-11e9-8a09-daaaa1d56855.gif)

**Comment by christinach** [comment]
![Screen Shot 2019-06-12 at 12 54 53 PM](https://user-images.githubusercontent.com/9905193/59370800-4f8b4b00-8d11-11e9-910e-6e652ba19b47.png)

**Comment by christinach** [comment]
updating the search bar width:
![Screen Shot 2019-06-12 at 1 23 23 PM](https://user-images.githubusercontent.com/9905193/59372356-54ea9480-8d15-11e9-8f5e-a789f3bd234b.png)

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/pulmap/pull/662
