### ISSUE TITLE
Geosearch tool isn't working properly

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#696]
- Searching a location does not trigger a search action in GBL. (#741 )
- Close icon "x" is doubled. (#742 )
- Can't close the search input box. (#742)

<img width="296" alt="Screenshot 2019-06-20 17 01 14" src="https://user-images.githubusercontent.com/784196/59884217-49cede80-937d-11e9-988f-678b4f8c4d78.png">

**Comment by christinach** [comment]
@eliotjordan I moved the first part in a different issue. https://github.com/pulibrary/pulmap/issues/741

**Comment by christinach** [comment]
and the 2 styling issues in #742

**Comment by eliotjordan** [comment]
Closed by #756
