### ISSUE TITLE
Decide on project name

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#70]
Lime
Pomelo
Mango
??

**Comment by escowles** [comment]
Please not pomelo -- so many P-names already.  So I'd go for Dragonfruit or Mango.

**Comment by jpstroop** [comment]
Artichoke, as in _globe artichoke_.

**Comment by escowles** [comment]
![apple](https://40.media.tumblr.com/c4b2de6976441d8a5f41f6addd919dc5/tumblr_nyk45oKag31sykpjyo1_500.jpg)
