### ISSUE TITLE
Thumbnails incorrectly positioned on ipad sized screens

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#746]
We could hide the thumbnails at this screen resolution or, maybe, have them appear below the document text.

![Simulator Screen Shot - iPad (5th generation) - 2019-06-27 at 09 22 57](https://user-images.githubusercontent.com/784196/60276026-78d6da00-98c0-11e9-9697-f1d8a1cd81bb.png)

**Comment by eliotjordan** [comment]
Child of #722

**Comment by christinach** [comment]
currently in production:
![Simulator Screen Shot - iPad Air (3rd generation) - 2019-06-28 at 10 25 20](https://user-images.githubusercontent.com/9905193/60349228-2c0e0480-998f-11e9-86e6-a210bc7d65f9.png)

**Comment by christinach** [comment]
production ipad screen:
![Simulator Screen Shot - iPad Air (3rd generation) - 2019-06-28 at 10 29 37](https://user-images.githubusercontent.com/9905193/60349463-a50d5c00-998f-11e9-9e28-a21ee5f5b986.png)

**Comment by christinach** [comment]
update to:
![Simulator Screen Shot - iPad Air (3rd generation) - 2019-06-28 at 12 03 05](https://user-images.githubusercontent.com/9905193/60355573-bad54e00-999c-11e9-99be-f903f4e326f0.png)
