### ISSUE TITLE
Bot is crawling WMS endpoints of non-existent records

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#781]
[Pulmap/production] ActionView::Template::Error: undefined method `references' for nil:NilClass

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/51978914)

```
ActionView::Template::Error: undefined method `references' for nil:NilClass
 _web_services.html.erb  3 __opt_pulmap_shared_bundle_ruby_______gems_geoblacklight_______app_views_catalog__web_services_html_erb(...)
[GEM_ROOT]/gems/geoblacklight-2.1.2/app/views/catalog/_web_services.html.erb:3:in `__opt_pulmap_shared_bundle_ruby_______gems_geoblacklight_______app_views_catalog__web_services_html_erb'
1 <% document ||= @documents.first %>
2 
3 <% document.references.refs.each do |reference| %>
4   <% if Settings.WEBSERVICES_SHOWN.include? reference.type.to_s %>
```

Solutions -
1. Block WMS endpoints in robots.txt.
1. Check that robots.txt file is updated.
1. Update partial in GBL to handle this situation gracefully.
1. Block offending bot.

**Comment by jrgriffiniii** [comment]
This still needs to be resolved by blocking the offending bot and ensuring that robots.txt is updated in the production environment.
