### ISSUE TITLE
Improve responsive design

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#79]

**Comment by eliotjordan** [comment]
<img width="881" alt="screenshot 2016-01-15 15 33 11" src="https://cloud.githubusercontent.com/assets/784196/12364590/875b0992-bb9d-11e5-8805-d5190e52cdf3.png">

**Comment by tampakis** [comment]
![index_view](https://cloud.githubusercontent.com/assets/4650153/12364646/d380e256-bb9d-11e5-8427-cf7240386537.png)

**Comment by tampakis** [comment]
The pagination portion (previous 1-10 next) and sort by/10 per page part should be centered when on 2 lines. Also true for Orangelight.

**Comment by axamei** [comment]
Broken:

- [ ] branding bar
- [ ] header / search bar
- [ ] search bar on home page
- [ ] bullets on home page
- [ ] footer
- [ ] results: applied parameters 
- [ ] results: pagination
- [ ] item record: search widgets
