### ISSUE TITLE
ARKs are broken for a number of pulmap Documents

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulmap#791]
Links for Sanborn Maps on 1917, 1918, and 1920 are breaking on: http://library.princeton.edu/libraries/firestone/rbsc/aids/sanborn/essex/newark.html

**Comment by jrgriffiniii** [comment]
Should https://maps.princeton.edu/catalog/princeton-sb397c18c be resolved from http://arks.princeton.edu/ark:/88435/n583xx34p?  It is described as sheet 108 and dated to 1917.

**Comment by jrgriffiniii** [comment]
https://maps.princeton.edu/catalog/princeton-wd376022k looks like a candidate for sheet 105 dated to 1918.

**Comment by eliotjordan** [comment]
Fixed.
