### ISSUE TITLE
Troubleshooting/debugging rails-reverse-proxy

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulmap#797]
This might be related to load balancing or other reverse proxy configuration settings, but I'm finding that the following offending line breaks GeoServer authentication support for me locally: https://github.com/axsuul/rails-reverse-proxy/blob/master/lib/reverse_proxy/client.rb#L60

**Comment by jrgriffiniii** [comment]
When I `cURL` using the authorization token, it does resolve properly:
```
% curl -H "Authorization: Basic SECRET" "https://geoserver.princeton.edu/geoserver/restricted-figgy/wms?service=WMS&request=GetMap&layers=restricted-figgy%3Ap-735d9ddb-d293-4454-b85b-e4d972f0708a&styles=&format=image%2Fpng&transparent=true&version=1.1.1&tiled=true&CRS=EPSG%3A900913&width=512&height=512&srs=EPSG%3A3857&bbox=-10958012.37496287,3443946.746416902,-10644926.307106787,3757032.8142729844"
```

That should be transmitted by the reverse proxy, and the auth. token is provided in the headers for the request when passed from the Rails controller.

**Comment by jrgriffiniii** [comment]
`rails-reverse-proxy` uses `Net::HTTP`: https://ruby-doc.org/stdlib-2.6.3/libdoc/net/http/rdoc/Net/HTTP.html.  When I replace this with a work-around of my own using `Faraday`, it does not have any problems sending/retrieving data in the Rails controller using an authorization token.

**Comment by jrgriffiniii** [comment]
I have a proposed solution in https://github.com/pulibrary/pulmap/tree/issues-797-jrgriffiniii-replace-rails-reverse-proxy I can use to open a pull request.

**Comment by escowles** [comment]
@jrgriffiniii I took a quick look at the diff, and everything there seems reasonable to me.  But I'm surprised that the existing reverse proxy gem isn't doing all that already (or providing a way for us to set custom headers, etc.)

**Comment by jrgriffiniii** [comment]
I'm getting the specs finished now (sorry, I had local Solr problems for testing).  My suspicion is that NGINX Plus might be using HTTP/2 somewhere and that was triggering the problems with `rails-reverse-proxy`

**Comment by kayiwa** [comment]
yes it does  use HTTP2 line 23 on `maps-staging.conf`
