### ISSUE TITLE
Missing `vector.svg` icon.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulmap#844]
## Backtrace

    line 78 of [PROJECT_ROOT]/app/helpers/application_helper.rb: placeholder_thumbnail_icon
    line 27 of [PROJECT_ROOT]/app/views/catalog/_index_split_default.html.erb: block in _app_views_catalog__index_split_default_html_erb__1568631240720114478_70001328497480
    line 2 of [PROJECT_ROOT]/app/views/catalog/_index_split_default.html.erb: _app_views_catalog__index_split_default_html_erb__1568631240720114478_70001328497480

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/61783766)

**Comment by jrgriffiniii** [comment]
This was triggered again by my last redeployment on 07/23/20 at 19:19 EDT.

**Comment by jrgriffiniii** [comment]
This was not fixed by redeploying the application to the production environment.

**Comment by jrgriffiniii** [comment]
I cannot locate this `vector.svg` icon anywhere in the precompiled assets within the production environment for pulmap, geoblacklight, or blacklight. I'm going to proceed with error handling for this.
