### ISSUE TITLE
Blacklight::Exceptions::RecordNotFound should not error, it should show a 404 page, and not raise an exception.

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#880]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/67218719)

**Comment by christinach** [comment]
https://maps.princeton.edu/catalog/uva-Newberry:GA_Newberry

**Comment by eliotjordan** [comment]
Cleaned thumbnail records.

**Comment by christinach** [comment]
https://maps.princeton.edu/catalog/uva-Virginia:CO_VA_poly Record not found today 03-19-2021

**Comment by hectorcorrea** [comment]
This error is still happening. Honeybadger just reported it (https://app.honeybadger.io/projects/54400/faults/67218719) when visiting https://maps.princeton.edu/catalog/tufts-bostonwardsprecints00. 

@eliotjordan @christinach - let me know if this should be a separate issue.

**Comment by christinach** [comment]
I deployed the changes. Closing this issue.
