### ISSUE TITLE
Handle TLS errors for remote WMS/WFS servers

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#908]
## Backtrace

    line 12 of [PROJECT_ROOT]/config/initializers/download.rb: initiate_download

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/72680376)

**Comment by jrgriffiniii** [comment]
https://maps.princeton.edu/download/sde-columbia-iscgm_honduras_2008_roadl?type=kmz raises TLS errors (please see https://geoserver.cul.columbia.edu)
