### ISSUE TITLE
Problems with downloads from maps2

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#924]
[Pulmap/production] ActionController::MissingFile: Cannot read file /opt/pulmap/shared/maplab/pulmap/downloads/stanford-cp768st2071-geojson.json

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/79048146)

**Comment by hackartisan** [comment]
It looks like the mount was lost on maps2 during the network event.

**Comment by hackartisan** [comment]
Ran the ansible playbook a few times and the mount successfully attached.
