### ISSUE TITLE
Make sure user, search tables are being expired

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulmap#926]
We think we are running the crons we need but the tables are very big so we're not sure.

**Comment by eliotjordan** [comment]
I _think_ the cron is working as it should, it's just that a *-ton of guest users are created everyday. I'll check back in next week (8/1) to see if the number has changed. As it stands, there are 267410 Users currently of which, 148 are non-guests.

**Comment by eliotjordan** [comment]
I think it's fine.
