### ISSUE TITLE
[Pulmap/production] RGeo::Error::InvalidGeometry: LinearRing failed ring test

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#975]
We get this error when a bounding box is not actually a box, e.g. it is a line.

It's trying to generate a url which it needs the bounding box for. There are probably other records like this, with the error getting triggered in other places.

This is an upstream data problem and we should at the very least talk to them about it.

In this case a 500 may be the correct behavior. If we're seeing this error in other contexts than this url generation, we may want to rescue it.

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/79938318)

**Comment by hackartisan** [comment]
The previous occurrence of this error has a comment "bad dataset". How do I confirm the validity of the dataset? What do I do if it is bad?
