### ISSUE TITLE
NetZero data does not have preview

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#978]
I believe there were issues because of completing the records before derivative generation completed. I fixed one of these by hand, but I'm not sure that's the best course of action for all of them.

From `digital-library` libanswers queue:

```
Name: Glenn Blackmon

Email: glenn.blackmon@commerce.wa.gov

Message:

Hi,
I'm trying to view the maps that are returned by this search:
https://maps.princeton.edu/?utf8=%E2%9C%93&search_field=all_fields&q=netzeroamerica
When I select one, I am able to see the extent and description, and there is a link to download the shapefile. But I can't view the map itself.

Maybe that's how it's supposed to work, and you're not providing online viewing of the maps, but I wanted to check about that.

Thanks

Current url: https://maps.princeton.edu/?utf8=%E2%9C%93&search_field=all_fields&q=netzeroamerica
```

**Comment by tpendragon** [comment]
We're going to fix this via fixing geoserver.

**Comment by eliotjordan** [comment]
Fixed for all except:
https://maps.princeton.edu/catalog/princeton-xs55mn54h
https://maps.princeton.edu/catalog/princeton-t148fs60q

There is something about the underlying data that locks up GeoServer entirely when a WMS service is called on these. I removed the layers from GeoServer manually so they won't cause issues when the page in Pulmap is loaded.
