### ISSUE TITLE
maps1 can't connect to maps2' Redis instance.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulmap#979]
I think this happened because maps1 just got moved to a new VM cluster. The firewall probably needs opened up. I emailed lsupport.

**Comment by hackartisan** [comment]
Looking at honeybadger it seems that maps1 is trying to connect to maps2. I updated the title.

Here's the honeybadger
https://app.honeybadger.io/projects/54400/faults/79040661

**Comment by hackartisan** [comment]
FW rules were updated
