### ISSUE TITLE
UX Testing

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#988]
- Review similar UX testing from other GeoBlacklight instances (Harvard, Big10)
- Collect user stories / critiques from stakeholders
- Plan and execute new round of Pulmap user testing

**Comment by sdellis** [comment]
Previous pulmap testing doc: https://docs.google.com/document/d/1WXqbO_LSHS9JyVeJure531966CYcwYrFnNcvWTkezik/edit

**Comment by eliotjordan** [comment]
Harvard GBL testing docs:
https://drive.google.com/drive/folders/1ZOslP652OzKa3p5cSgaLdbryIYgEG5ph?usp=sharing
