### ISSUE TITLE
Mosaics should have a viewer.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulmap#990]
We can set up leaflet.js and configure it to point to the mosaic JSON to provide a basic viewer to users.

Part of this is already in Geoblacklight for TMS.

Strategy here is to add XYZ reference and viewer to GeoBlacklight and update to Pulmap to latest 3.x version.

The geoblacklight PR with an XYZ viewer is: https://github.com/geoblacklight/geoblacklight/pull/1111

We might switch to TileJSON if there's a performance issue with XYZ.

**Comment by tpendragon** [comment]
We might have to use a leaflet.js plugin.

**Comment by eliotjordan** [comment]
Strategy here is to add XYZ reference and viewer to GeoBlacklight and update to Pulmap to latest 3.x version.

**Comment by tpendragon** [comment]
We're going to use https://github.com/kartena/leaflet-tilejson and the tileserver's tilejson, like so: https://map-tiles-staging.princeton.edu/mosaicjson/tilejson.json?id=f75a1e91ade3427a82a109d321d47cbf

**Comment by eliotjordan** [comment]
Closed by #1033
